# roles/dnsmasq/tasks/main.yml
---
- name: Install Dnsmasq
  ansible.builtin.dnf:
    pkg: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq
